[project]
name = "likeit"
version = "0.1.0"
description = "LikeIt is a social media platform for onchain content creators to connect with their audience powered by Base."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "eth-ape>=0.8.32",
    "ruff>=0.11.7",
]
